### PR TITLE
fix: diagnostic of SUIT Manifests

### PR DESCRIPTION
**Pull request by kentakayama**
This PR is mainly an improvement, but contains some bug fixes.
I've checked each SUIT Manifest diagnostic notation is compatible with its hex binary using [cbor.me](https://cbor.me).

Changes
- comment out "digest:" and "signatures:" in the authentication-wrapper
- replace `F6` with `null` because it is encoded hex value
- add `) >>` at the end of signature
- fix the order of `source-component` and `compression-info` in example 4
- remove unnecessary `,` at the end of arrays and maps
- use `"` for text string
- fix white space

### CODE REVIEW

**Comment by bremoran** [comment]
Unfortunately, these are generated files; they are created here:

https://gitlab.arm.com/research/ietf-suit/suit-tool/-/blob/master/examples/make-examples.sh

I'll need to update the suit-tool to correct these.

**Comment by kentakayama** [comment]
The original texts in this PR are manually created by myself based on the I-D, and now the [libcsuit](https://github.com/yuichitk/libcsuit) supports to generate such notations:

```
$ make -f Makefile.parser test | egrep -e "^    " | sed "s/(verified)//g"
    / SUIT_Envelope = /
    107({
        / authentication-wrapper / 2: << [
            / digest: / << [
                / algorithm-id: / -16 / SHA-256 /,
                / digest-bytes: / h'6658ea560262696dd1f13b782239a064da7c6c5cbaf52fded428a6fc83c7e5af'
            ] >>,
            / signatures: / << 18([
                / protected: / << {
                    / alg / 1: -7 / ES256 /
                } >>,
                / unprotected: / {
                },
                / payload: / null,
                / signature: / h'01d9cbf51b1ccadf839ec867da85735118ba4c1b513f5df60583e8dd7f8ce4274cd2e2a0f70f8832bfea63983172e77a951e9a36e74cada19321b903a097e4e7'
            ]) >>
        ] >>,
        / manifest / 3: << {
            / manifest-version / 1: 1,
            / manifest-sequence-number / 2: 0,
            / common / 3: << {
                / components / 2: [
                    [h'00']
                ],
                / common-sequence / 4: << [
                    / directive-override-parameters / 20, {
                        / vendor-id / 1: h'fa6b4a53d5ad5fdfbe9de663e4d41ffe' / fa6b4a53-d5ad-5fdf-be9d-e663e4d41ffe /,
                        / class-id / 2: h'1492af1425695e48bf429b2d51f2ab45' / 1492af14-2569-5e48-bf42-9b2d51f2ab45 /,
                        / image-digest / 3: << [
                            / algorithm-id: / -16 / SHA-256 /,
                            / digest-bytes: / h'00112233445566778899aabbccddeeff0123456789abcdeffedcba9876543210'
                        ] >>,
                        / image-size / 14: 34768
                    },
                    / condition-vendor-identifier / 1, 15,
                    / condition-class-identifier / 2, 15
                ] >>
            } >>,
            / validate / 7: << [
                / condition-image-match / 3, 15
            ] >>,
            / run / 9: << [
                / directive-run / 23, 2
            ] >>
        } >>
    })
...
```

They are tested:
- the parser generates CBOR diagnostic notation from each example binary file and 
- it can be converted into original binary with [cbor.me](https://cbor.me)

Feel free to let me know if you want to use libcsuit.

**Comment by bremoran** [comment]
Hi Ken, with the updates to the suit-tool (see here: https://gitlab.arm.com/research/ietf-suit/suit-tool) this should now be fixed.

**Comment by kentakayama** [comment]
Perfect! Then I'll close this PR.

**Pull request closed without merging**
